########################
#     LunarUtility     #
# By RefineDevelopment #
########################

#Disabled cooldowns for 1.9+ because of LC API Issue
COOLDOWN:
  ENDERPEARL: #Sends cooldown on enderpearl throw
    ENABLE: true
    ICON: "ENDER_PEARL"
    DELAY: 16
  GAPPLE: #Sends cooldown when a gapple is eaten
    ENABLE: false
    ICON: "GOLDEN_APPLE"
    DELAY: 45
  COMBAT: #Sends cooldown when a fight happens | both to the damager and the target
    ENABLE: false
    ICON: "DIAMOND_SWORD"
    DELAY: 30
#Don't set the cooldown to 0 or else the plugin won't work!
#You have to restart the server whenever you change the delay.

REQUIRE-LUNAR:
  ENABLED: false
  MESSAGE: "&cLunar Client is required to play on the server! <space> &cDownload at &olunarclient.com/download" #<space> adds a new line

MODS:
  DISABLE-ALL-MODS: false
  DISABLE-MODS:
    ENABLED: false
    MODS:
     - "skyblockAddons"

WAYPOINT:
  ENABLED: true #If false, it won't load all the waypoints below
  WAYPOINTS:
   - Spawn: # The same name as the waypoint.
       x: 0
       y: 100
       z: 0
       name: "Spawn"
       world: "world"
       color: 0xFF0000 # MUST be a hexadecimal number of a color
       forced: true
       visible: true

NAMETAG:
  ENABLE: true #Needs Restart
  TICKS: "40" #1 second = 20 ticks | Every x seconds the nametag should update
  FIRST: "&7[<status> &bLC&7]"
  SECOND:
    ENABLE: true
    TAG: "<player_name>" # use <player_displayname> for disguise support

OTHER:
  ENABLED: "&aON"
  DISABLED: "&cOFF"

MESSAGES:
  MAIN:
    RELOAD: "&6LunarUtility &ehas been reloaded."
    OFFLINE: "&cThat player doesn't exist."
  LUNAR-COMMAND:
    PLAYER: "&6You are currently <status> &eLunarClient."
    TARGET: "&e<target> &6is currently <status> &eLunarClient."
  LUNAR-STAFF-COMMAND:
    PLAYER: "&aYou have enabled all LunarClient staff mods."
    TARGET: "&aYou have enabled all LunarClient staff mods for <target>."
    TO-TARGET: "&aAll LunarClient mods have been enabled for you by <player>."
  LUNAR-USERS-COMMAND:
    SEPERATOR: "&7, "
    MESSAGE:
      - "&7&m-----------------------"
      - "&b&lLunarClient Users &7[<totalUsers>/100]"
      - "<playerList>"
      - "&7&m-----------------------"