########################
#     LunarUtility     #
# By RefineDevelopment #
########################

NAMETAG:
  ENABLE: true #Needs Restart
  TICKS: "40" #1 second = 20 ticks | Every x seconds the nametag should update
  FIRST: "&7[<status> &bLC&7]"
  SECOND:
    ENABLE: true
    TAG: "<player_name>" # use <player_displayname> for disguise support

WAYPOINTS:
  ENABLE: true
  NAME: "Spawn"
  WORLD: "world"

OTHER:
  ENABLED: "&aON"
  DISABLED: "&cOFF"

#Disabled cooldowns for 1.9+ because of LC API Issue
COOLDOWN:
  ENDERPEARL:
    ENABLE: true
    DELAY: 16
  GAPPLE:
    ENABLE: false
    DELAY: 5
#Don't set the cooldown to 0 or else the plugin won't work!
#You have to restart the server whenever you change the delay.

REQUIRE-LUNAR:
  ENABLED: false
  MESSAGE: "&cLunar Client is required to play on the server! <space> &cDownload at &olunarclient.com/download" #<space> adds a new line

MESSAGES:
  MAIN:
    RELOAD: "&6LunarUtility &ehas been reloaded."
    OFFLINE: "&cThat player doesn't exist."
  LUNAR-COMMAND:
    PLAYER: "&6You are currently <status> &eLunarClient."
    TARGET: "&e<target> &6is currently <status> &eLunarClient."
  LUNAR-STAFF-COMMAND:
    PLAYER: "&aYou have enabled all LunarClient staff mods."
    TARGET: "&aYou have enabled all LunarClient staff mods for <target>."
    TO-TARGET: "&aAll LunarClient mods have been enabled for you by <player>."
  LUNAR-USERS-COMMAND:
    SEPERATOR: "&7, "
    MESSAGE:
      - "&7&m-----------------------"
      - "&b&lLunarClient Users &7[<totalUsers>/100]"
      - "<playerList>"
      - "&7&m-----------------------"