########################
#    LunarUtility V1.1 #
#       By Dubai       #
########################

COOLDOWN:
  ENDERPEARL:
    DELAY: 16
#Don't set the cooldown to 0 or else the plugin wont work!
MESSAGES:
  MAIN:
    PERMISSION: "&cNo Permission."
    RELOAD: "&6LunarUtility &ehas been reloaded."
    OFFLINE: "&cThat player doesn't exist."
  LUNAR-COMMAND:
    #Available placeholders: <player> <status>
    PLAYER: "&6You are currently <status> &eLunarClient."
    #Available placeholders: <target> <status>
    TARGET: "&e<target> &6is currently <status> &eLunarClient."
  LUNAR-STAFF-COMMAND:
    PLAYER: "&aYou have enabled all LunarClient staff mods."
    #Available placeholders: <target>
    TARGET: "&aYou have enabled all LunarClient staff mods for <target>."

WAYPOINTS:
  ENABLED: true
  NAME: "Spawn"
  WORLD: "world"