########################
#  LunarUtility V1.4   #
#     By Dubai#1454    #
########################

NAMETAG:
  ENABLE: true
  FIRST: "&7[<status> &bLC&7]"
  SECOND: "<player_name>" # use <player_displayname> for disguise support

SERVER-RULES:
  SERVER_HANDLES_WAYPOINTS: false
  LEGACY_ENCHANTING: false
  COMPETITIVE_GAME: false
  SHADERS_DISABLED: false
  LEGACY_COMBAT: false

WAYPOINTS:
  ENABLE: true
  NAME: "Spawn"
  WORLD: "world"

COOLDOWN:
  ENDERPEARL:
    ENABLE: true
    DELAY: 16
  GAPPLE:
    ENABLE: true
    DELAY: 5
#Don't set the cooldown to 0 or else the plugin wont work!
#You have to restart the server whenever you change the delay. (not possible to fix)

MESSAGES:
  MAIN:
    RELOAD: "&6LunarUtility &ehas been reloaded."
    OFFLINE: "&cThat player doesn't exist."
  LUNAR-COMMAND:
    PLAYER: "&6You are currently <status> &eLunarClient."
    TARGET: "&e<target> &6is currently <status> &eLunarClient."
  LUNAR-STAFF-COMMAND:
    PLAYER: "&aYou have enabled all LunarClient staff mods."
    TARGET: "&aYou have enabled all LunarClient staff mods for <target>."
    TO-TARGET: "&aAll LunarClient mods have been enabled for you by <player>."
  LUNAR-USERS-COMMAND:
    LIST:
      - "&7&m-----------------------"
      - "&b&lLunarClient Users"
      - "<list>"
      - "&7&m-----------------------"